### PR TITLE
#1 - Correction of html tags without closing.

### PR DESCRIPTION
**Pull request by maveius**
Please look this, it is very important chages, because tags without need closed tag which has content was not implemented. Like:

``` html
<input type="checkbox" />Checkbox description
```

### CODE REVIEW

**Comment by asika32764** [comment]
Hi, thank you for contribution.

Could you send this PR to main repository? That we can split it to all subtree.
https://github.com/ventoviro/windwalker

Thank you.

**Comment by asika32764** [comment]
I looked your code and I understand what you want.

But IMHO, it is not a standard behavior that will confuse other developers.

If someone wants to build a checkbox, they should use this code

``` php
new HtmlElement('input', null, ['type' => 'checkbox']) . ' Content';
```

OR

``` php
new HtmlElement('input', null, ['type' => 'checkbox']) . new HtmlElement('label', 'Content', ['for' => 'xxx'])
```

That will be a good practice for HTML standard and keep same behavior to all element objects.

**Comment by maveius** [comment]
Ok. I know how to get around, but I think that is not good way to insert **null** in the content, and if somebody want to close html tag in parenthesis, and don't need concatenate whith other String, becouse library can help him and is more flexible. Why the content string must be after HtmlElement ? I think the library should be more inteligent and should not forcing one (or two) right way.

I hope so that developers will not confused ! Maybe ask more developers about it ? I am very interested in.

I use Your library to develop [my library] (https://github.com/maveius/liphte) and [homepage] (http://maveius.pl/liphte/) , and I can use another hacks but i thoutht that the better way is change it at source.

**Comment by asika32764** [comment]
I agree it will be weird that we always add a NULL as content, but I think it is still semantic enough because people can know this element has no content since NULL means `empty`.

To think in XML or DOM way, a content after a self-closed element is not allowed, it means this text outside this element, so I will prefer add this text after element object if we need HTML support.

Even if I accept this idea, we can still not do this change at current time, this behavior will break the B/C.

To your opinion, I think a better and flexible way is use chaining pattern:

``` php
(new HtmlElement('input'))->set('type', 'checkbox');
```

It will be a cleaner way and understandable, keep constructor same behavior to avoid confusing but provides multiple ways to do same thing.

**Pull request closed without merging**
